name: DoorProtector
main: DoorProtector\main
version: "3.0.0"
api: 4.0.0
author: narapon
description: ドア保護用プラグインです
commands:
 dp:
  usage: /dp <subcommand>
  aliases: [d]
  description: DoorProtectionのコマンドです
  permission: dp.command
 setdp:
  aliases: [setd]
  usage: /setdp <subcommand>
  description: DoorProtectionの設定用コマンドです
  permission: setdp.command
permissions:
 dp.command:
  default: true
 setdp.command:
  default: op
 dp.permission:
  default: op
