name: DoorProtector
main: DoorProtector\main
version: "2.2.0"
api: 3.0.0
author: narapon
description: ドア保護用プラグインです
commands:
 dp:
  usage: /dp <subcommand>
  aliases: [d]
  description: DoorProtectionのコマンドです
 setdp:
  aliases: [setd]
  usage: /setdp <subcommand>
  description: DoorProtectionの設定用コマンドです
  permission: setdp.command
permissions:
 setdp.command:
  default: op
